#Base image for building the Go application
FROM ubuntu AS build
RUN apt-get update && apt-get install -y golang-go
ENV GO111MODULE=off
COPY . .
# Build the Go application
FROM scratch 
COPY --from=build /app /app
ENTRYPOINT ["/app"]